### ISSUE TITLE
Text change

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/decentralized-portal#21]
from _- Actively managed portfolio with crypto only exposure -_ 
to _- Actively managed fund with crypto only exposure -

**Comment by jennazenk** [comment]
do you actually want to leave this ? It was dummy data for me as placeholder, but I can leave it :)

**Comment by retotrinkler** [comment]
From `Statistiques`
`Statistics`

**Comment by retotrinkler** [comment]
might be prob cleaner to remove

**Comment by retotrinkler** [comment]
in settings
- Change reference currency: MLN ; this can't be changed on fund level
- Claim rewards: 7 MLN ; prob placeholder which should be zero
- Shut down fund ; could be actual option

**Comment by retotrinkler** [comment]
nice in participation w 5% plus/minsu

**Comment by jennazenk** [comment]
:)

**Comment by retotrinkler** [comment]
would change: `Coming soon ;)` to `In development`

**Comment by jennazenk** [comment]
Sure! Should we even keep the statistics panel as not implemented yet ? 
(will be implemented a soon as I can start working on functions to efficiently read from the blockchain)

**Comment by retotrinkler** [comment]
in `Overview` would be cool if
- Last Price: 0.2290
- Bid : 0.2286
- Ask: 0.2291
prefill price in `Place an order`
